/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IMemeFactory {
  export type MemeCreationParamsStruct = {
    name: string;
    symbol: string;
    tokenId: BigNumberish;
    tokenOffset: BigNumberish;
    nativeOffset: BigNumberish;
    totalSupply: BigNumberish;
    saleAmount: BigNumberish;
    reservedSupply: BigNumberish;
    initialDeposit: BigNumberish;
    whitelistStartTs: BigNumberish;
    whitelistEndTs: BigNumberish;
    stakeEndTs: BigNumberish;
    lockEndTs: BigNumberish;
    lockedToken: AddressLike;
    listingSqrtPriceX96: BigNumberish;
    listingFeeTier: BigNumberish;
  };

  export type MemeCreationParamsStructOutput = [
    name: string,
    symbol: string,
    tokenId: bigint,
    tokenOffset: bigint,
    nativeOffset: bigint,
    totalSupply: bigint,
    saleAmount: bigint,
    reservedSupply: bigint,
    initialDeposit: bigint,
    whitelistStartTs: bigint,
    whitelistEndTs: bigint,
    stakeEndTs: bigint,
    lockEndTs: bigint,
    lockedToken: string,
    listingSqrtPriceX96: bigint,
    listingFeeTier: bigint
  ] & {
    name: string;
    symbol: string;
    tokenId: bigint;
    tokenOffset: bigint;
    nativeOffset: bigint;
    totalSupply: bigint;
    saleAmount: bigint;
    reservedSupply: bigint;
    initialDeposit: bigint;
    whitelistStartTs: bigint;
    whitelistEndTs: bigint;
    stakeEndTs: bigint;
    lockEndTs: bigint;
    lockedToken: string;
    listingSqrtPriceX96: bigint;
    listingFeeTier: bigint;
  };

  export type InitializationParamsStruct = {
    tokenImplementation: AddressLike;
    memeImplementation: AddressLike;
    vaultImplementation: AddressLike;
    uniswapV3Factory: AddressLike;
    native: AddressLike;
    signerAddress: AddressLike;
    treasury1: AddressLike;
    treasury2: AddressLike;
    supplyReserveTreasury: AddressLike;
    tradingFeeRate: BigNumberish;
    treasury1TradingFeeCommission: BigNumberish;
    listingFeeRate: BigNumberish;
    creationFee: BigNumberish;
  };

  export type InitializationParamsStructOutput = [
    tokenImplementation: string,
    memeImplementation: string,
    vaultImplementation: string,
    uniswapV3Factory: string,
    native: string,
    signerAddress: string,
    treasury1: string,
    treasury2: string,
    supplyReserveTreasury: string,
    tradingFeeRate: bigint,
    treasury1TradingFeeCommission: bigint,
    listingFeeRate: bigint,
    creationFee: bigint
  ] & {
    tokenImplementation: string;
    memeImplementation: string;
    vaultImplementation: string;
    uniswapV3Factory: string;
    native: string;
    signerAddress: string;
    treasury1: string;
    treasury2: string;
    supplyReserveTreasury: string;
    tradingFeeRate: bigint;
    treasury1TradingFeeCommission: bigint;
    listingFeeRate: bigint;
    creationFee: bigint;
  };
}

export interface MemeFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createMeme"
      | "createMemeWithoutLaunching"
      | "creationFee"
      | "forLaunching"
      | "getLockVaultAddress"
      | "getMemeAddress"
      | "getPumpContractAddress"
      | "initialize"
      | "initializeWithoutLaunching"
      | "listingFeeRate"
      | "memeImplementation"
      | "native"
      | "owner"
      | "renounceOwnership"
      | "setCreationFee"
      | "setForLaunching"
      | "setListingFeeRate"
      | "setMemeImplementation"
      | "setNative"
      | "setSignerAddress"
      | "setSupplyReserveTreasury"
      | "setTokenImplementation"
      | "setTradingFeeRate"
      | "setTreasury1"
      | "setTreasury1TradingFeeCommission"
      | "setTreasury2"
      | "setUniV3Factory"
      | "setVaultImplementation"
      | "signerAddress"
      | "supplyReserveTreasury"
      | "tokenImplementation"
      | "tradingFeeRate"
      | "transferOwnership"
      | "treasury1"
      | "treasury1TradingFeeCommission"
      | "treasury2"
      | "uniswapV3Factory"
      | "vaultImplementation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ConfigurationSet"
      | "DistributeSupplyToStakers"
      | "FeeConfigurationSet"
      | "Initialized"
      | "LockVaultCreated"
      | "MemeCreated"
      | "MemeCreatedWithoutLaunching"
      | "MemeImplementationSet"
      | "OwnershipTransferred"
      | "PayCreationFee"
      | "TokenImplementationSet"
      | "VaultImplementationSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createMeme",
    values: [IMemeFactory.MemeCreationParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "createMemeWithoutLaunching",
    values: [string, string, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "creationFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "forLaunching",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLockVaultAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMemeAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPumpContractAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [IMemeFactory.InitializationParamsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeWithoutLaunching",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "listingFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "memeImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "native", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCreationFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setForLaunching",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setListingFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMemeImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNative",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSignerAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSupplyReserveTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTradingFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury1",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury1TradingFeeCommission",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury2",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUniV3Factory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultImplementation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "signerAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supplyReserveTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tradingFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury1", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treasury1TradingFeeCommission",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "uniswapV3Factory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vaultImplementation",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "createMeme", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createMemeWithoutLaunching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "forLaunching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLockVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMemeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPumpContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeWithoutLaunching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listingFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "memeImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "native", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreationFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForLaunching",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setListingFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMemeImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNative", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSignerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSupplyReserveTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTradingFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury1TradingFeeCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUniV3Factory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signerAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyReserveTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tradingFeeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury1", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasury1TradingFeeCommission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "uniswapV3Factory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultImplementation",
    data: BytesLike
  ): Result;
}

export namespace ConfigurationSetEvent {
  export type InputTuple = [
    signerAddress: AddressLike,
    native: AddressLike,
    uniswapV3Factory: AddressLike,
    forLaunching: boolean,
    factory: AddressLike
  ];
  export type OutputTuple = [
    signerAddress: string,
    native: string,
    uniswapV3Factory: string,
    forLaunching: boolean,
    factory: string
  ];
  export interface OutputObject {
    signerAddress: string;
    native: string;
    uniswapV3Factory: string;
    forLaunching: boolean;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributeSupplyToStakersEvent {
  export type InputTuple = [
    token: AddressLike,
    treasury: AddressLike,
    amount: BigNumberish,
    factory: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    treasury: string,
    amount: bigint,
    factory: string
  ];
  export interface OutputObject {
    token: string;
    treasury: string;
    amount: bigint;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeConfigurationSetEvent {
  export type InputTuple = [
    treasury1: AddressLike,
    treasury2: AddressLike,
    supplyReserveTreasury: AddressLike,
    tradingFeeRate: BigNumberish,
    treasury1TradingFeeCommission: BigNumberish,
    listingFeeRate: BigNumberish,
    creationFee: BigNumberish,
    factory: AddressLike
  ];
  export type OutputTuple = [
    treasury1: string,
    treasury2: string,
    supplyReserveTreasury: string,
    tradingFeeRate: bigint,
    treasury1TradingFeeCommission: bigint,
    listingFeeRate: bigint,
    creationFee: bigint,
    factory: string
  ];
  export interface OutputObject {
    treasury1: string;
    treasury2: string;
    supplyReserveTreasury: string;
    tradingFeeRate: bigint;
    treasury1TradingFeeCommission: bigint;
    listingFeeRate: bigint;
    creationFee: bigint;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockVaultCreatedEvent {
  export type InputTuple = [
    token: AddressLike,
    lockedToken: AddressLike,
    vault: AddressLike,
    tokenId: BigNumberish,
    stakeEndTime: BigNumberish,
    lockEndTime: BigNumberish,
    factory: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    lockedToken: string,
    vault: string,
    tokenId: bigint,
    stakeEndTime: bigint,
    lockEndTime: bigint,
    factory: string
  ];
  export interface OutputObject {
    token: string;
    lockedToken: string;
    vault: string;
    tokenId: bigint;
    stakeEndTime: bigint;
    lockEndTime: bigint;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemeCreatedEvent {
  export type InputTuple = [
    token: AddressLike,
    meme: AddressLike,
    creator: AddressLike,
    totalSupply: BigNumberish,
    saleAmount: BigNumberish,
    reservedSupply: BigNumberish,
    tokenOffset: BigNumberish,
    nativeOffset: BigNumberish,
    tokenId: BigNumberish,
    factory: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    meme: string,
    creator: string,
    totalSupply: bigint,
    saleAmount: bigint,
    reservedSupply: bigint,
    tokenOffset: bigint,
    nativeOffset: bigint,
    tokenId: bigint,
    factory: string
  ];
  export interface OutputObject {
    token: string;
    meme: string;
    creator: string;
    totalSupply: bigint;
    saleAmount: bigint;
    reservedSupply: bigint;
    tokenOffset: bigint;
    nativeOffset: bigint;
    tokenId: bigint;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemeCreatedWithoutLaunchingEvent {
  export type InputTuple = [
    token: AddressLike,
    tokenId: BigNumberish,
    factory: AddressLike
  ];
  export type OutputTuple = [token: string, tokenId: bigint, factory: string];
  export interface OutputObject {
    token: string;
    tokenId: bigint;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MemeImplementationSetEvent {
  export type InputTuple = [arg0: AddressLike, factory: AddressLike];
  export type OutputTuple = [arg0: string, factory: string];
  export interface OutputObject {
    arg0: string;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PayCreationFeeEvent {
  export type InputTuple = [
    token: AddressLike,
    recipient: AddressLike,
    creationFee: BigNumberish,
    factory: AddressLike
  ];
  export type OutputTuple = [
    token: string,
    recipient: string,
    creationFee: bigint,
    factory: string
  ];
  export interface OutputObject {
    token: string;
    recipient: string;
    creationFee: bigint;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenImplementationSetEvent {
  export type InputTuple = [arg0: AddressLike, factory: AddressLike];
  export type OutputTuple = [arg0: string, factory: string];
  export interface OutputObject {
    arg0: string;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultImplementationSetEvent {
  export type InputTuple = [arg0: AddressLike, factory: AddressLike];
  export type OutputTuple = [arg0: string, factory: string];
  export interface OutputObject {
    arg0: string;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MemeFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MemeFactory;
  waitForDeployment(): Promise<this>;

  interface: MemeFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMeme: TypedContractMethod<
    [params: IMemeFactory.MemeCreationParamsStruct],
    [[string, string] & { token: string; meme: string }],
    "nonpayable"
  >;

  createMemeWithoutLaunching: TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _tokenId: BigNumberish,
      _totalSupply: BigNumberish,
      _supplyRecipient: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  creationFee: TypedContractMethod<[], [bigint], "view">;

  forLaunching: TypedContractMethod<[], [boolean], "view">;

  getLockVaultAddress: TypedContractMethod<
    [_tokenId: BigNumberish],
    [string],
    "view"
  >;

  getMemeAddress: TypedContractMethod<
    [_tokenId: BigNumberish],
    [string],
    "view"
  >;

  getPumpContractAddress: TypedContractMethod<
    [tokenAddress: AddressLike],
    [string],
    "view"
  >;

  initialize: TypedContractMethod<
    [params: IMemeFactory.InitializationParamsStruct],
    [void],
    "nonpayable"
  >;

  initializeWithoutLaunching: TypedContractMethod<
    [_implementation: AddressLike],
    [void],
    "nonpayable"
  >;

  listingFeeRate: TypedContractMethod<[], [bigint], "view">;

  memeImplementation: TypedContractMethod<[], [string], "view">;

  native: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setCreationFee: TypedContractMethod<
    [_creationFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setForLaunching: TypedContractMethod<
    [_forLaunching: boolean],
    [void],
    "nonpayable"
  >;

  setListingFeeRate: TypedContractMethod<
    [_listingFeeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMemeImplementation: TypedContractMethod<
    [_implementation: AddressLike],
    [void],
    "nonpayable"
  >;

  setNative: TypedContractMethod<[_native: AddressLike], [void], "nonpayable">;

  setSignerAddress: TypedContractMethod<
    [_signer: AddressLike],
    [void],
    "nonpayable"
  >;

  setSupplyReserveTreasury: TypedContractMethod<
    [_supplyReserveTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setTokenImplementation: TypedContractMethod<
    [_implementation: AddressLike],
    [void],
    "nonpayable"
  >;

  setTradingFeeRate: TypedContractMethod<
    [_tradingFeeRate: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury1: TypedContractMethod<
    [_treasury1: AddressLike],
    [void],
    "nonpayable"
  >;

  setTreasury1TradingFeeCommission: TypedContractMethod<
    [_treasury1TradingFeeCommission: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury2: TypedContractMethod<
    [_treasury2: AddressLike],
    [void],
    "nonpayable"
  >;

  setUniV3Factory: TypedContractMethod<
    [_univ3Factory: AddressLike],
    [void],
    "nonpayable"
  >;

  setVaultImplementation: TypedContractMethod<
    [_implementation: AddressLike],
    [void],
    "nonpayable"
  >;

  signerAddress: TypedContractMethod<[], [string], "view">;

  supplyReserveTreasury: TypedContractMethod<[], [string], "view">;

  tokenImplementation: TypedContractMethod<[], [string], "view">;

  tradingFeeRate: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury1: TypedContractMethod<[], [string], "view">;

  treasury1TradingFeeCommission: TypedContractMethod<[], [bigint], "view">;

  treasury2: TypedContractMethod<[], [string], "view">;

  uniswapV3Factory: TypedContractMethod<[], [string], "view">;

  vaultImplementation: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMeme"
  ): TypedContractMethod<
    [params: IMemeFactory.MemeCreationParamsStruct],
    [[string, string] & { token: string; meme: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createMemeWithoutLaunching"
  ): TypedContractMethod<
    [
      _name: string,
      _symbol: string,
      _tokenId: BigNumberish,
      _totalSupply: BigNumberish,
      _supplyRecipient: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "creationFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "forLaunching"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getLockVaultAddress"
  ): TypedContractMethod<[_tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getMemeAddress"
  ): TypedContractMethod<[_tokenId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPumpContractAddress"
  ): TypedContractMethod<[tokenAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [params: IMemeFactory.InitializationParamsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initializeWithoutLaunching"
  ): TypedContractMethod<[_implementation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "listingFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "memeImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "native"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCreationFee"
  ): TypedContractMethod<[_creationFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setForLaunching"
  ): TypedContractMethod<[_forLaunching: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setListingFeeRate"
  ): TypedContractMethod<[_listingFeeRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMemeImplementation"
  ): TypedContractMethod<[_implementation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNative"
  ): TypedContractMethod<[_native: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSignerAddress"
  ): TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSupplyReserveTreasury"
  ): TypedContractMethod<
    [_supplyReserveTreasury: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTokenImplementation"
  ): TypedContractMethod<[_implementation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTradingFeeRate"
  ): TypedContractMethod<[_tradingFeeRate: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury1"
  ): TypedContractMethod<[_treasury1: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury1TradingFeeCommission"
  ): TypedContractMethod<
    [_treasury1TradingFeeCommission: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury2"
  ): TypedContractMethod<[_treasury2: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUniV3Factory"
  ): TypedContractMethod<[_univ3Factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVaultImplementation"
  ): TypedContractMethod<[_implementation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signerAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "supplyReserveTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenImplementation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tradingFeeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasury1TradingFeeCommission"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "uniswapV3Factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "vaultImplementation"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ConfigurationSet"
  ): TypedContractEvent<
    ConfigurationSetEvent.InputTuple,
    ConfigurationSetEvent.OutputTuple,
    ConfigurationSetEvent.OutputObject
  >;
  getEvent(
    key: "DistributeSupplyToStakers"
  ): TypedContractEvent<
    DistributeSupplyToStakersEvent.InputTuple,
    DistributeSupplyToStakersEvent.OutputTuple,
    DistributeSupplyToStakersEvent.OutputObject
  >;
  getEvent(
    key: "FeeConfigurationSet"
  ): TypedContractEvent<
    FeeConfigurationSetEvent.InputTuple,
    FeeConfigurationSetEvent.OutputTuple,
    FeeConfigurationSetEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "LockVaultCreated"
  ): TypedContractEvent<
    LockVaultCreatedEvent.InputTuple,
    LockVaultCreatedEvent.OutputTuple,
    LockVaultCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MemeCreated"
  ): TypedContractEvent<
    MemeCreatedEvent.InputTuple,
    MemeCreatedEvent.OutputTuple,
    MemeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MemeCreatedWithoutLaunching"
  ): TypedContractEvent<
    MemeCreatedWithoutLaunchingEvent.InputTuple,
    MemeCreatedWithoutLaunchingEvent.OutputTuple,
    MemeCreatedWithoutLaunchingEvent.OutputObject
  >;
  getEvent(
    key: "MemeImplementationSet"
  ): TypedContractEvent<
    MemeImplementationSetEvent.InputTuple,
    MemeImplementationSetEvent.OutputTuple,
    MemeImplementationSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PayCreationFee"
  ): TypedContractEvent<
    PayCreationFeeEvent.InputTuple,
    PayCreationFeeEvent.OutputTuple,
    PayCreationFeeEvent.OutputObject
  >;
  getEvent(
    key: "TokenImplementationSet"
  ): TypedContractEvent<
    TokenImplementationSetEvent.InputTuple,
    TokenImplementationSetEvent.OutputTuple,
    TokenImplementationSetEvent.OutputObject
  >;
  getEvent(
    key: "VaultImplementationSet"
  ): TypedContractEvent<
    VaultImplementationSetEvent.InputTuple,
    VaultImplementationSetEvent.OutputTuple,
    VaultImplementationSetEvent.OutputObject
  >;

  filters: {
    "ConfigurationSet(address,address,address,bool,address)": TypedContractEvent<
      ConfigurationSetEvent.InputTuple,
      ConfigurationSetEvent.OutputTuple,
      ConfigurationSetEvent.OutputObject
    >;
    ConfigurationSet: TypedContractEvent<
      ConfigurationSetEvent.InputTuple,
      ConfigurationSetEvent.OutputTuple,
      ConfigurationSetEvent.OutputObject
    >;

    "DistributeSupplyToStakers(address,address,uint256,address)": TypedContractEvent<
      DistributeSupplyToStakersEvent.InputTuple,
      DistributeSupplyToStakersEvent.OutputTuple,
      DistributeSupplyToStakersEvent.OutputObject
    >;
    DistributeSupplyToStakers: TypedContractEvent<
      DistributeSupplyToStakersEvent.InputTuple,
      DistributeSupplyToStakersEvent.OutputTuple,
      DistributeSupplyToStakersEvent.OutputObject
    >;

    "FeeConfigurationSet(address,address,address,uint256,uint256,uint256,uint256,address)": TypedContractEvent<
      FeeConfigurationSetEvent.InputTuple,
      FeeConfigurationSetEvent.OutputTuple,
      FeeConfigurationSetEvent.OutputObject
    >;
    FeeConfigurationSet: TypedContractEvent<
      FeeConfigurationSetEvent.InputTuple,
      FeeConfigurationSetEvent.OutputTuple,
      FeeConfigurationSetEvent.OutputObject
    >;

    "Initialized(uint8)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "LockVaultCreated(address,address,address,uint256,uint256,uint256,address)": TypedContractEvent<
      LockVaultCreatedEvent.InputTuple,
      LockVaultCreatedEvent.OutputTuple,
      LockVaultCreatedEvent.OutputObject
    >;
    LockVaultCreated: TypedContractEvent<
      LockVaultCreatedEvent.InputTuple,
      LockVaultCreatedEvent.OutputTuple,
      LockVaultCreatedEvent.OutputObject
    >;

    "MemeCreated(address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,address)": TypedContractEvent<
      MemeCreatedEvent.InputTuple,
      MemeCreatedEvent.OutputTuple,
      MemeCreatedEvent.OutputObject
    >;
    MemeCreated: TypedContractEvent<
      MemeCreatedEvent.InputTuple,
      MemeCreatedEvent.OutputTuple,
      MemeCreatedEvent.OutputObject
    >;

    "MemeCreatedWithoutLaunching(address,uint256,address)": TypedContractEvent<
      MemeCreatedWithoutLaunchingEvent.InputTuple,
      MemeCreatedWithoutLaunchingEvent.OutputTuple,
      MemeCreatedWithoutLaunchingEvent.OutputObject
    >;
    MemeCreatedWithoutLaunching: TypedContractEvent<
      MemeCreatedWithoutLaunchingEvent.InputTuple,
      MemeCreatedWithoutLaunchingEvent.OutputTuple,
      MemeCreatedWithoutLaunchingEvent.OutputObject
    >;

    "MemeImplementationSet(address,address)": TypedContractEvent<
      MemeImplementationSetEvent.InputTuple,
      MemeImplementationSetEvent.OutputTuple,
      MemeImplementationSetEvent.OutputObject
    >;
    MemeImplementationSet: TypedContractEvent<
      MemeImplementationSetEvent.InputTuple,
      MemeImplementationSetEvent.OutputTuple,
      MemeImplementationSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PayCreationFee(address,address,uint256,address)": TypedContractEvent<
      PayCreationFeeEvent.InputTuple,
      PayCreationFeeEvent.OutputTuple,
      PayCreationFeeEvent.OutputObject
    >;
    PayCreationFee: TypedContractEvent<
      PayCreationFeeEvent.InputTuple,
      PayCreationFeeEvent.OutputTuple,
      PayCreationFeeEvent.OutputObject
    >;

    "TokenImplementationSet(address,address)": TypedContractEvent<
      TokenImplementationSetEvent.InputTuple,
      TokenImplementationSetEvent.OutputTuple,
      TokenImplementationSetEvent.OutputObject
    >;
    TokenImplementationSet: TypedContractEvent<
      TokenImplementationSetEvent.InputTuple,
      TokenImplementationSetEvent.OutputTuple,
      TokenImplementationSetEvent.OutputObject
    >;

    "VaultImplementationSet(address,address)": TypedContractEvent<
      VaultImplementationSetEvent.InputTuple,
      VaultImplementationSetEvent.OutputTuple,
      VaultImplementationSetEvent.OutputObject
    >;
    VaultImplementationSet: TypedContractEvent<
      VaultImplementationSetEvent.InputTuple,
      VaultImplementationSetEvent.OutputTuple,
      VaultImplementationSetEvent.OutputObject
    >;
  };
}
